package com.pd.beertimer.util

const val CHANNEL_ID = "BEER_TIME_APP_CHANNEL"
const val SHARED_PREF_DRINKING_TIMES = "SHARED_PREF_DRINKING_TIMES"
const val SHARED_PREF_DRINKING_CALCULATOR = "SHARED_PREF_DRINKING_CALCULATOR"
const val SHARED_PREF_ROOM_INIT = "SHARED_PREF_ROOM_INIT"
const val SHARED_PREF_BEER_TIME = "BT_BESTE_APP_DA"

const val INTENT_EXTRA_NOTIFICATION_MESSAGE = "INTENT_MESSAGE_NOTIFICATION"
const val NOTIFICATION_ID = 1337
