package com.example.beertime.util

const val CHANNEL_ID = "BEER_TIME_APP_CHANNEL"
const val SHARED_PREF_DRINKING_TIMES = "SHARED_PREF_DRINKING_TIMES"
const val SHARED_PREF_BEER_TIME = "BT_BESTE_APP_DA"
const val NOTIFICATION_ID = 1337